//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiskMasterWallet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Address { get; set; }
        public decimal Balance { get; set; }
        public long Block { get; set; }
        public string FriendlyName { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string PublicKey { get; set; }
        public string SecretHash { get; set; }
        public System.DateTime LastTransactionsUpdate { get; set; }
    }
}
